encoder_list = [ce.BackwardDifferenceEncoder(feature_list),
ce.BaseNEncoder(feature_list),
ce.BinaryEncoder(feature_list),
ce.CatBoostEncoder(feature_list),
ce.HashingEncoder(feature_list),
ce.HelmertEncoder(feature_list),
ce.JamesSteinEncoder(feature_list),
ce.LeaveOneOutEncoder(feature_list),
ce.MEstimateEncoder(feature_list),
ce.OneHotEncoder(feature_list),
ce.OrdinalEncoder(feature_list),
ce.SumEncoder(feature_list),
ce.PolynomialEncoder(feature_list),
ce.TargetEncoder(feature_list),
ce.WOEEncoder(feature_list)]